on:
  pull_request:
    branches: "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.x, 1.21.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Git
        env:
          GOPRIVATE: github.com/sanekee/limi/*
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://sanekee:${TOKEN}@github.com".insteadOf "https://github.com"
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: limi-repo
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        if: matrix.os == 'ubuntu-latest' && matrix.go-version == '1.20.x'
        with:
          version: v1.55
          working-directory: limi-repo
      - name: Windows Test
        if: matrix.os == 'windows-latest'
        working-directory: limi-repo
        run: |
          go test ./...
      - name: Unix Test
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        working-directory: limi-repo
        run: |
          go test -coverprofile cover.out -covermode set ./...
          coverage="$(go tool cover -func=cover.out | grep total: | sed 's/[^0-9.\]//g')"
          echo "Coverage: ${coverage}%"
      - name: Integration Test Prep
        working-directory: limi-repo/example/rest
        run: |
          go run main.go &
      - name: Integration Test
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        working-directory: limi-repo/example/rest/scripts
        run: |
          sh ./test.sh
